production:
  delivery_method: :smtp
  smtp_settings:
    address: "smtp.sendgrid.net" 
    port: 587
    authentication: :plain
    domain: ENV['DOMAIN']
    user_name: ENV['SENDGRID_USERNAME']
    password: ENV['SENDGRID_PASSWORD']
